[app_settings]
info = "Some general app settings"
nifti_dir = '/home/scchat/lxd_dir/ubuntu/u-mamba_3dslicer/temp/nifti'
seg_dir = '/home/scchat/lxd_dir/ubuntu/u-mamba_3dslicer/temp/seg'
seg_2d_dir = '/home/scchat/lxd_dir/ubuntu/u-mamba_3dslicer/temp/seg_2d'