FROM nvidia/cuda:12.5.0-base-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt update && \
    apt install -y python3.12 python3.12-distutils python3.12-dev python3.12-venv curl git && \
    apt upgrade -y && \
    apt clean
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.12 1
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

WORKDIR /app

# RUN groupadd -r user && useradd -m --no-log-init -r -g user user
# # required by cv2
# RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

# RUN mkdir -p /opt/app /inputs /outputs \
#     && chown user:user /opt/app /inputs /outputs

# USER user
# WORKDIR /opt/app
# ENV PATH="/home/user/.local/bin:${PATH}"

# RUN python -m pip install --user -U pip && python -m pip install --user pip-tools

# COPY --chown=user:user . .
# RUN pip install -e .
